import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, Sparkles } from 'lucide-react';

const TermsOfService = () => {
  return (
    <div className="min-h-screen w-full flex items-center justify-center relative overflow-hidden px-4 py-12">
      <div className="w-full max-w-4xl bg-white/70 backdrop-blur-xl rounded-3xl shadow-2xl border border-amber-200/50 p-8 md:p-12 my-8">
        
        <div className="flex flex-col items-center text-center mb-8">
          <div className="w-16 h-16 bg-gradient-to-br from-amber-400 via-orange-500 to-amber-600 rounded-2xl shadow-lg flex items-center justify-center mb-4">
            <Sparkles className="w-8 h-8 text-white" />
          </div>
          <h1 className="text-3xl md:text-4xl font-bold text-amber-900">Terms of Service</h1>
          <p className="text-amber-700/80 mt-2">Last Updated: October 26, 2023</p>
        </div>

        <div className="prose prose-amber max-w-none text-amber-800/90 prose-headings:text-amber-900 prose-strong:text-amber-900">
          
          <p>Welcome to AI Resume Crafter! These Terms of Service (&ldquo;Terms&rdquo;) govern your use of our website, services, and software (collectively, the &ldquo;Service&rdquo;). By accessing or using our Service, you agree to be bound by these Terms.</p>

          <h2>1. Description of Service</h2>
          <p>AI Resume Crafter is a tool that uses artificial intelligence to help you create professional resumes. You provide your personal and professional information, and our Service uses AI models and templates to generate a formatted resume document.</p>

          <h2>2. User Accounts</h2>
          <p>To use our Service, you must create an account using Google Sign-In. You are responsible for safeguarding your account and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use of your account. You must provide accurate and complete information and keep your account information updated.</p>

          <h2>3. User Data and Content</h2>
          <ul>
            <li><strong>Your Content:</strong> You own all the information and content you provide to the Service, including personal details, work history, skills, and education (&ldquo;User Content&rdquo;).</li>
            <li><strong>License to Us:</strong> By using the Service, you grant AI Resume Crafter a worldwide, non-exclusive, royalty-free license to use, process, reproduce, and display your User Content solely for the purpose of operating, providing, and improving the Service. This includes using your data to train our AI models to enhance the quality of our resume generation.</li>
            <li><strong>Responsibility:</strong> You are solely responsible for your User Content and ensuring it is accurate, lawful, and does not violate any third-party rights. We are not responsible for the accuracy or legality of the content generated based on your input.</li>
          </ul>
          
          <h2>4. AI-Generated Content</h2>
          <p>The resumes generated by our Service are created by artificial intelligence. While we strive for accuracy and quality, AI-generated content may contain errors, inaccuracies, or omissions. You are responsible for reviewing and verifying the final resume document before use. AI Resume Crafter is not liable for any decisions made based on the content of the generated resume, including but not limited to job application outcomes.</p>
          
          <h2>5. Intellectual Property</h2>
          <p>Excluding your User Content, the Service itself, including the website, branding, design, templates, software, and all underlying technology, are the exclusive property of AI Resume Crafter and its licensors. You may not copy, modify, or reverse engineer any part of our Service.</p>

          <h2>6. Prohibited Conduct</h2>
          <p>You agree not to use the Service for any unlawful purpose or to:
            <ul>
                <li>Submit false, misleading, or inaccurate information.</li>
                <li>Infringe on the intellectual property rights of others.</li>
                <li>Transmit any viruses, malware, or other malicious code.</li>
                <li>Attempt to disrupt or compromise the integrity or security of the Service.</li>
            </ul>
          </p>
          
          <h2>7. Termination</h2>
          <p>You can terminate this agreement at any time by deleting your account from the dashboard. We may suspend or terminate your access to the Service at any time, with or without cause, if you violate these Terms.</p>
          
          <h2>8. Disclaimers and Limitation of Liability</h2>
          <p>THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; WITHOUT ANY WARRANTIES, EXPRESS OR IMPLIED. AI RESUME CRAFTER DISCLAIMS ALL WARRANTIES, INCLUDING THE WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. IN NO EVENT SHALL AI RESUME CRAFTER BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING OUT OF OR RELATED TO YOUR USE OF THE SERVICE.</p>

          <h2>9. Changes to Terms</h2>
          <p>We reserve the right to modify these Terms at any time. We will notify you of any changes by posting the new Terms on this page. Your continued use of the Service after any such changes constitutes your acceptance of the new Terms.</p>
          
          <h2>10. Contact Us</h2>
          <p>If you have any questions about these Terms, please contact us at [Your Contact Email or Link].</p>
        </div>

        <div className="text-center mt-12">
            <Link to="/auth/sign-in" className="inline-flex items-center gap-2 text-amber-800 hover:text-amber-900 font-semibold transition-colors">
                <ArrowLeft size={16} />
                <span>Back to Login</span>
            </Link>
        </div>

      </div>
    </div>
  );
};

export default TermsOfService; 